import Menu from './menu.svg'
import Search from './search.svg'
import CrescentMoon from './crescent-moon.svg'
import Notifications from './notifications.svg'
import Settings from './settings.svg'
import User from './user.svg'
import LeftArrow from './left-arrow.svg'
import Home from './home.svg'
import Team from './team.svg'
import Notebook from './notebook.svg'
import Receipt from './receipt.svg'
import Calendar from './calendar.svg'
import FAQ from './faq.svg'
import LineChart from './line-chart.svg'
import PieChart from './pie.svg'
import BarChart from './bar-chart.svg'
import Map from './map.svg'
import Download from './download.svg'
import Sun from './sun.svg'
import Shield from './shield.svg'
import ShieldManager from './shield-manager.svg'
import Mail from './mail.svg'
import SalesSymbol from './sales-symbol.svg'
import NewClient from './user-add.svg'
import Traffic from './traffic.svg'


export {Menu, Search, CrescentMoon, Notifications, Settings, User, LeftArrow, Home, Team, Notebook, Receipt, Calendar, FAQ, LineChart, BarChart, Map, PieChart, Download, Sun, Shield, ShieldManager, Mail, SalesSymbol, NewClient, Traffic}